---
- hosts: all
  tasks:
     - name: Install telnet package
       package:
          name: telnet
          state: present 

     - name: Show messgae telnet
       debug:
         msg: "Show messgae telnet"
